
package soapinterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CategoriesService", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CategoriesService {


    /**
     * 
     * @param cat
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isCategorie", targetNamespace = "http://www.polytech.fr", className = "soapinterface.IsCategorie")
    @ResponseWrapper(localName = "isCategorieResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.IsCategorieResponse")
    @Action(input = "http://www.polytech.fr/CategoriesService/isCategorieRequest", output = "http://www.polytech.fr/CategoriesService/isCategorieResponse")
    public boolean isCategorie(
        @WebParam(name = "cat", targetNamespace = "")
        String cat);

    /**
     * 
     * @return
     *     returns java.util.List<soapinterface.Categories>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCategories", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetCategories")
    @ResponseWrapper(localName = "getCategoriesResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetCategoriesResponse")
    @Action(input = "http://www.polytech.fr/CategoriesService/getCategoriesRequest", output = "http://www.polytech.fr/CategoriesService/getCategoriesResponse")
    public List<Categories> getCategories();

}
