
package soapinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClassTestService", targetNamespace = "http://www.test.fr", wsdlLocation = "http://localhost:9000/?wsdl")
public class ClassTestService
    extends Service
{

    private final static URL CLASSTESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLASSTESTSERVICE_EXCEPTION;
    private final static QName CLASSTESTSERVICE_QNAME = new QName("http://www.test.fr", "ClassTestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLASSTESTSERVICE_WSDL_LOCATION = url;
        CLASSTESTSERVICE_EXCEPTION = e;
    }

    public ClassTestService() {
        super(__getWsdlLocation(), CLASSTESTSERVICE_QNAME);
    }

    public ClassTestService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLASSTESTSERVICE_QNAME, features);
    }

    public ClassTestService(URL wsdlLocation) {
        super(wsdlLocation, CLASSTESTSERVICE_QNAME);
    }

    public ClassTestService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLASSTESTSERVICE_QNAME, features);
    }

    public ClassTestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClassTestService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClassTest
     */
    @WebEndpoint(name = "ClassTestPort")
    public ClassTest getClassTestPort() {
        return super.getPort(new QName("http://www.test.fr", "ClassTestPort"), ClassTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClassTest
     */
    @WebEndpoint(name = "ClassTestPort")
    public ClassTest getClassTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.test.fr", "ClassTestPort"), ClassTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLASSTESTSERVICE_EXCEPTION!= null) {
            throw CLASSTESTSERVICE_EXCEPTION;
        }
        return CLASSTESTSERVICE_WSDL_LOCATION;
    }

}
