
package soapinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClientService", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientService {


    /**
     * 
     * @param usr
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "verifyUsername", targetNamespace = "http://www.polytech.fr", className = "soapinterface.VerifyUsername")
    @ResponseWrapper(localName = "verifyUsernameResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.VerifyUsernameResponse")
    @Action(input = "http://www.polytech.fr/ClientService/verifyUsernameRequest", output = "http://www.polytech.fr/ClientService/verifyUsernameResponse")
    public boolean verifyUsername(
        @WebParam(name = "usr", targetNamespace = "")
        String usr);

    /**
     * 
     * @param client
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createAccount", targetNamespace = "http://www.polytech.fr", className = "soapinterface.CreateAccount")
    @ResponseWrapper(localName = "createAccountResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.CreateAccountResponse")
    @Action(input = "http://www.polytech.fr/ClientService/createAccountRequest", output = "http://www.polytech.fr/ClientService/createAccountResponse")
    public boolean createAccount(
        @WebParam(name = "client", targetNamespace = "")
        Client client);

    /**
     * 
     * @param usr
     * @param mdp
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://www.polytech.fr", className = "soapinterface.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.LoginResponse")
    @Action(input = "http://www.polytech.fr/ClientService/loginRequest", output = "http://www.polytech.fr/ClientService/loginResponse")
    public boolean login(
        @WebParam(name = "usr", targetNamespace = "")
        String usr,
        @WebParam(name = "mdp", targetNamespace = "")
        String mdp);

    /**
     * 
     * @param newCli
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://www.polytech.fr", className = "soapinterface.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.UpdateResponse")
    @Action(input = "http://www.polytech.fr/ClientService/updateRequest", output = "http://www.polytech.fr/ClientService/updateResponse")
    public boolean update(
        @WebParam(name = "newCli", targetNamespace = "")
        Client newCli);

}
