
package soapinterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CommandesService", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommandesService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validerCommande", targetNamespace = "http://www.polytech.fr", className = "soapinterface.ValiderCommande")
    @ResponseWrapper(localName = "validerCommandeResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.ValiderCommandeResponse")
    @Action(input = "http://www.polytech.fr/CommandesService/validerCommandeRequest", output = "http://www.polytech.fr/CommandesService/validerCommandeResponse")
    public boolean validerCommande(
        @WebParam(name = "arg0", targetNamespace = "")
        Commande arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soapinterface.Commande
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCommande", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetCommande")
    @ResponseWrapper(localName = "getCommandeResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetCommandeResponse")
    @Action(input = "http://www.polytech.fr/CommandesService/getCommandeRequest", output = "http://www.polytech.fr/CommandesService/getCommandeResponse")
    public Commande getCommande(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<soapinterface.Commande>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUserCommandes", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetUserCommandes")
    @ResponseWrapper(localName = "getUserCommandesResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetUserCommandesResponse")
    @Action(input = "http://www.polytech.fr/CommandesService/getUserCommandesRequest", output = "http://www.polytech.fr/CommandesService/getUserCommandesResponse")
    public List<Commande> getUserCommandes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns soapinterface.Commande
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ajouterProduit", targetNamespace = "http://www.polytech.fr", className = "soapinterface.AjouterProduit")
    @ResponseWrapper(localName = "ajouterProduitResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.AjouterProduitResponse")
    @Action(input = "http://www.polytech.fr/CommandesService/ajouterProduitRequest", output = "http://www.polytech.fr/CommandesService/ajouterProduitResponse")
    public Commande ajouterProduit(
        @WebParam(name = "arg0", targetNamespace = "")
        Commande arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns soapinterface.Commande
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "applyShipping", targetNamespace = "http://www.polytech.fr", className = "soapinterface.ApplyShipping")
    @ResponseWrapper(localName = "applyShippingResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.ApplyShippingResponse")
    @Action(input = "http://www.polytech.fr/CommandesService/applyShippingRequest", output = "http://www.polytech.fr/CommandesService/applyShippingResponse")
    public Commande applyShipping(
        @WebParam(name = "arg0", targetNamespace = "")
        Commande arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
