
package soapinterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<soapinterface.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduitsIndex", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsIndex")
    @ResponseWrapper(localName = "getProduitsIndexResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsIndexResponse")
    @Action(input = "http://www.polytech.fr/ProductService/getProduitsIndexRequest", output = "http://www.polytech.fr/ProductService/getProduitsIndexResponse")
    public List<Product> getProduitsIndex();

    /**
     * 
     * @param cat
     * @return
     *     returns java.util.List<soapinterface.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduitsCategorie", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsCategorie")
    @ResponseWrapper(localName = "getProduitsCategorieResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsCategorieResponse")
    @Action(input = "http://www.polytech.fr/ProductService/getProduitsCategorieRequest", output = "http://www.polytech.fr/ProductService/getProduitsCategorieResponse")
    public List<Product> getProduitsCategorie(
        @WebParam(name = "cat", targetNamespace = "")
        String cat);

    /**
     * 
     * @param id
     * @return
     *     returns soapinterface.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduit", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduit")
    @ResponseWrapper(localName = "getProduitResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitResponse")
    @Action(input = "http://www.polytech.fr/ProductService/getProduitRequest", output = "http://www.polytech.fr/ProductService/getProduitResponse")
    public Product getProduit(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param tokens
     * @return
     *     returns java.util.List<soapinterface.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduitsSearch", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsSearch")
    @ResponseWrapper(localName = "getProduitsSearchResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetProduitsSearchResponse")
    @Action(input = "http://www.polytech.fr/ProductService/getProduitsSearchRequest", output = "http://www.polytech.fr/ProductService/getProduitsSearchResponse")
    public List<Product> getProduitsSearch(
        @WebParam(name = "tokens", targetNamespace = "")
        List<String> tokens);

}
