
package soapinterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProductService", targetNamespace = "localhost:8085/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductService {


    /**
     * 
     * @return
     *     returns java.util.List<soapinterface.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduitsIndex", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduitsIndex")
    @ResponseWrapper(localName = "getProduitsIndexResponse", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduitsIndexResponse")
    @Action(input = "localhost:8085/ProductService/getProduitsIndexRequest", output = "localhost:8085/ProductService/getProduitsIndexResponse")
    public List<Product> getProduitsIndex();

    /**
     * 
     * @param id
     * @return
     *     returns soapinterface.Product
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduit", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduit")
    @ResponseWrapper(localName = "getProduitResponse", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduitResponse")
    @Action(input = "localhost:8085/ProductService/getProduitRequest", output = "localhost:8085/ProductService/getProduitResponse")
    public Product getProduit(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param tokens
     * @return
     *     returns java.util.List<soapinterface.Product>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getProduitsSearch", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduitsSearch")
    @ResponseWrapper(localName = "getProduitsSearchResponse", targetNamespace = "localhost:8085/", className = "soapinterface.GetProduitsSearchResponse")
    @Action(input = "localhost:8085/ProductService/getProduitsSearchRequest", output = "localhost:8085/ProductService/getProduitsSearchResponse")
    public List<Product> getProduitsSearch(
        @WebParam(name = "tokens", targetNamespace = "")
        List<String> tokens);

}
