
package soapinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ShippingServiceService", targetNamespace = "http://www.polytech.fr", wsdlLocation = "http://localhost:9000/shipping?wsdl")
public class ShippingServiceService
    extends Service
{

    private final static URL SHIPPINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SHIPPINGSERVICESERVICE_EXCEPTION;
    private final static QName SHIPPINGSERVICESERVICE_QNAME = new QName("http://www.polytech.fr", "ShippingServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9000/shipping?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SHIPPINGSERVICESERVICE_WSDL_LOCATION = url;
        SHIPPINGSERVICESERVICE_EXCEPTION = e;
    }

    public ShippingServiceService() {
        super(__getWsdlLocation(), SHIPPINGSERVICESERVICE_QNAME);
    }

    public ShippingServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SHIPPINGSERVICESERVICE_QNAME, features);
    }

    public ShippingServiceService(URL wsdlLocation) {
        super(wsdlLocation, SHIPPINGSERVICESERVICE_QNAME);
    }

    public ShippingServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SHIPPINGSERVICESERVICE_QNAME, features);
    }

    public ShippingServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShippingServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ShippingService
     */
    @WebEndpoint(name = "ShippingServicePort")
    public ShippingService getShippingServicePort() {
        return super.getPort(new QName("http://www.polytech.fr", "ShippingServicePort"), ShippingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShippingService
     */
    @WebEndpoint(name = "ShippingServicePort")
    public ShippingService getShippingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.polytech.fr", "ShippingServicePort"), ShippingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SHIPPINGSERVICESERVICE_EXCEPTION!= null) {
            throw SHIPPINGSERVICESERVICE_EXCEPTION;
        }
        return SHIPPINGSERVICESERVICE_WSDL_LOCATION;
    }

}
