
package soapinterface;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ShippingService", targetNamespace = "http://www.polytech.fr")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ShippingService {


    /**
     * 
     * @return
     *     returns java.util.List<soapinterface.Shipping>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShippings", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShippings")
    @ResponseWrapper(localName = "getShippingsResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShippingsResponse")
    @Action(input = "http://www.polytech.fr/ShippingService/getShippingsRequest", output = "http://www.polytech.fr/ShippingService/getShippingsResponse")
    public List<Shipping> getShippings();

    /**
     * 
     * @param arg0
     * @return
     *     returns soapinterface.Shipping
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShipping", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShipping")
    @ResponseWrapper(localName = "getShippingResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShippingResponse")
    @Action(input = "http://www.polytech.fr/ShippingService/getShippingRequest", output = "http://www.polytech.fr/ShippingService/getShippingResponse")
    public Shipping getShipping(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns soapinterface.Shipping
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getShippingByName", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShippingByName")
    @ResponseWrapper(localName = "getShippingByNameResponse", targetNamespace = "http://www.polytech.fr", className = "soapinterface.GetShippingByNameResponse")
    @Action(input = "http://www.polytech.fr/ShippingService/getShippingByNameRequest", output = "http://www.polytech.fr/ShippingService/getShippingByNameResponse")
    public Shipping getShippingByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
